name: Build

on:
  push:
    branches: [develop]
    tags-ignore:
      - '**'

  pull_request:
    branches: [develop]

  release:
    types: [published]

jobs:
  Verify:
    runs-on: ubuntu-latest

    env:
      GOPATH: /home/runner/go

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      with:
        fetch-depth: 0

    - name: Set Go version
      id: go_version
      run: |
        GO_VERSION=$(cat .palantir/go-version | sed 's/^go//' )
        echo "::set-output name=version::${GO_VERSION}"

    - name: Set up Go
      uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
      with:
        go-version: ${{ steps.go_version.outputs.version }}

    - name: Cache Godel assets
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ~/.godel
        key: ${{ runner.os }}-godel-${{ hashFiles('godelw', 'godel/config/godel.yml') }}
        restore-keys: |
          ${{ runner.os }}-godel-

    - name: Verify
      run: ./godelw verify --apply=false
